.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH OLIVE-GTK 1 "August 21, 2006"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
olive-gtk \- GTK-based GUI for Bazaar
.SH SYNOPSIS
.B olive-gtk
.SH DESCRIPTION
You should run Olive from your Application menu, Programming submenu.
.PP
.SH OPTIONS
The program has no command line options.
.SH AUTHOR
Olive was written by Szilveszter Farkas (Phanatic) <Szilveszter.Farkas@gmail.com>.
.PP
This manual page was written by Szilveszter Farkas (Phanatic)
<Szilveszter.Farkas@gmail.com>, for the Ubuntu project (but may be used by others).
