.TH OLIVE-GTK 1 "April 24, 2007"
.SH NAME
olive-gtk \- GTK+ frontend for Bazaar
.SH SYNOPSIS
.B olive-gtk
.SH DESCRIPTION
Olive aims to be a full-featured graphical frontend for the Bazaar (bzr)
source code management tool.
.SH SEE ALSO
.BR bzr (1).
.SH AUTHOR
\fBolive-gtk\fP was written by Szilveszter Farkas <szilveszter.farkas@gmail.com>
.PP
This manual page was written by Chris Lamb <chris@chris-lamb.co.uk>,
for the Debian project (but may be used by others).
